"""This file contains the graph schema for the application."""

from typing import Annotated

from langgraph.graph.message import add_messages
from pydantic import (
    BaseModel,
    Field,
)


class GraphState(BaseModel):
    """State definition for the LangGraph Agent/Workflow."""

    messages: Annotated[list, add_messages] = Field(
        default_factory=list, description="The messages in the conversation"
    )
    long_term_memory: str = Field(default="", description="The long term memory of the conversation")


class MarketingGraphState(GraphState):
    """Extended state for the TikTok Marketing Agent with strategy pre-planning."""

    strategy: str = Field(
        default="",
        description="Internal strategy plan generated by the strategist node before the chat node runs",
    )
    consensus_used: bool = Field(
        default=False, description="Whether multi-model consensus was executed for this turn"
    )
    consensus_note: str = Field(
        default="", description="Summary of consensus outcome to be surfaced to the user"
    )
